create_clock -period 5.000 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_n]
set_property PACKAGE_PIN R4 [get_ports sys_clk_p]
set_property PACKAGE_PIN T4 [get_ports sys_clk_n]

set_property PACKAGE_PIN Y22 [get_ports vout_clk]
set_property PACKAGE_PIN V22 [get_ports {vout_data[0]}]
set_property PACKAGE_PIN Y18 [get_ports {vout_data[1]}]
set_property PACKAGE_PIN Y19 [get_ports {vout_data[2]}]
set_property PACKAGE_PIN W19 [get_ports {vout_data[3]}]
set_property PACKAGE_PIN W20 [get_ports {vout_data[4]}]
set_property PACKAGE_PIN Y21 [get_ports {vout_data[5]}]
set_property PACKAGE_PIN U21 [get_ports {vout_data[6]}]
set_property PACKAGE_PIN T21 [get_ports {vout_data[7]}]
set_property PACKAGE_PIN W21 [get_ports {vout_data[8]}]
set_property PACKAGE_PIN W22 [get_ports {vout_data[9]}]
set_property PACKAGE_PIN T20 [get_ports {vout_data[10]}]
set_property PACKAGE_PIN AB18 [get_ports {vout_data[11]}]
set_property PACKAGE_PIN AA18 [get_ports {vout_data[12]}]
set_property PACKAGE_PIN AA19 [get_ports {vout_data[13]}]
set_property PACKAGE_PIN AB20 [get_ports {vout_data[14]}]
set_property PACKAGE_PIN AA20 [get_ports {vout_data[15]}]
set_property PACKAGE_PIN AA21 [get_ports {vout_data[16]}]
set_property PACKAGE_PIN AB22 [get_ports {vout_data[17]}]
set_property PACKAGE_PIN AB21 [get_ports {vout_data[18]}]
set_property PACKAGE_PIN W17 [get_ports {vout_data[19]}]
set_property PACKAGE_PIN V17 [get_ports {vout_data[20]}]
set_property PACKAGE_PIN V20 [get_ports {vout_data[21]}]
set_property PACKAGE_PIN U20 [get_ports {vout_data[22]}]
set_property PACKAGE_PIN V19 [get_ports {vout_data[23]}]
set_property PACKAGE_PIN U22 [get_ports vout_de]
set_property PACKAGE_PIN T18 [get_ports vout_hs]
set_property PACKAGE_PIN Y17 [get_ports hdmi_nreset_v10]
set_property PACKAGE_PIN L18 [get_ports hdmi_nreset]
set_property PACKAGE_PIN R18 [get_ports vout_vs]
set_property PACKAGE_PIN H13 [get_ports hdmi_scl]
set_property PACKAGE_PIN G13 [get_ports hdmi_sda]

set_property IOSTANDARD LVCMOS33 [get_ports vout_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {vout_data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports vout_de]
set_property IOSTANDARD LVCMOS33 [get_ports vout_hs]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_nreset]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_nreset_v10]
set_property IOSTANDARD LVCMOS33 [get_ports vout_vs]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_scl]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_sda]

set_property IOB TRUE [get_ports {vout_data[*]}]
set_property IOB TRUE [get_ports vout_de]
set_property IOB TRUE [get_ports vout_hs]
set_property IOB TRUE [get_ports vout_vs]

set_property SLEW FAST [get_ports {vout_data[*]}]
set_property SLEW FAST [get_ports vout_de]
set_property SLEW FAST [get_ports vout_hs]
set_property SLEW FAST [get_ports vout_vs]

set_property DRIVE 12 [get_ports {vout_data[12]}]
set_property DRIVE 16 [get_ports vout_clk]
set_property DRIVE 12 [get_ports vout_de]
set_property DRIVE 12 [get_ports vout_hs]

set_property PACKAGE_PIN F15 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
#####################################################
set_property PACKAGE_PIN W15 [get_ports {cam_sda}]
set_property PACKAGE_PIN W16 [get_ports {cam_scl}]
set_property PACKAGE_PIN W12 [get_ports {cam_xclk}]
set_property PACKAGE_PIN Y12 [get_ports {cam_data[0]}]
set_property PACKAGE_PIN V10 [get_ports {cam_data[1]}]
set_property PACKAGE_PIN U15 [get_ports {cam_data[2]}]
set_property PACKAGE_PIN V15 [get_ports {cam_data[3]}]
set_property PACKAGE_PIN Y11 [get_ports {cam_data[4]}]
set_property PACKAGE_PIN W10 [get_ports {cam_data[5]}]
set_property PACKAGE_PIN V13 [get_ports {cam_data[6]}]
set_property PACKAGE_PIN V14 [get_ports {cam_data[7]}]
set_property PACKAGE_PIN T15 [get_ports {cam_pclk}]
set_property PACKAGE_PIN W11 [get_ports {cam_href}]
set_property PACKAGE_PIN T14 [get_ports {cam_vsync}]
set_property PACKAGE_PIN AA10 [get_ports {cam_rst_n}]
set_property PACKAGE_PIN AA11 [get_ports {cam_pwdn}]

set_property IOSTANDARD LVCMOS33 [get_ports cam_sda]
set_property IOSTANDARD LVCMOS33 [get_ports cam_scl]
set_property IOSTANDARD LVCMOS33 [get_ports cam_xclk]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports cam_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports cam_href]
set_property IOSTANDARD LVCMOS33 [get_ports cam_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports cam_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports cam_pwdn]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cam_pclk]
set_input_delay -clock [get_clocks cam_pclk]  2.200 [get_ports {cam_data[*]}]
set_input_delay -clock [get_clocks cam_pclk]  2.200 [get_ports cam_href]
set_input_delay -clock [get_clocks cam_pclk] -min -add_delay 2.200 [get_ports cam_vsync]
set_input_delay -clock [get_clocks cam_pclk] -max -add_delay 4.000 [get_ports cam_vsync]
