# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/iCloudDrive/course/EE332/lab/final/code/0528/0528.srcs/sources_1/ip/mmcm/mmcm.xci
# IP: The module: 'mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/iCloudDrive/course/EE332/lab/final/code/0528/cam2hdmi.gen/sources_1/ip/mmcm/mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/iCloudDrive/course/EE332/lab/final/code/0528/cam2hdmi.gen/sources_1/ip/mmcm/mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/iCloudDrive/course/EE332/lab/final/code/0528/cam2hdmi.gen/sources_1/ip/mmcm/mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/iCloudDrive/course/EE332/lab/final/code/0528/0528.srcs/sources_1/ip/mmcm/mmcm.xci
# IP: The module: 'mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/iCloudDrive/course/EE332/lab/final/code/0528/cam2hdmi.gen/sources_1/ip/mmcm/mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/iCloudDrive/course/EE332/lab/final/code/0528/cam2hdmi.gen/sources_1/ip/mmcm/mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/iCloudDrive/course/EE332/lab/final/code/0528/cam2hdmi.gen/sources_1/ip/mmcm/mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
