# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/iCloudDrive/course/EE332/lab/final/code/0528/0528.srcs/sources_1/ip/req_pend_fifo/req_pend_fifo.xci
# IP: The module: 'req_pend_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/iCloudDrive/course/EE332/lab/final/code/0528/cam2hdmi.gen/sources_1/ip/req_pend_fifo/req_pend_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'req_pend_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/iCloudDrive/course/EE332/lab/final/code/0528/cam2hdmi.gen/sources_1/ip/req_pend_fifo/req_pend_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'req_pend_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/iCloudDrive/course/EE332/lab/final/code/0528/0528.srcs/sources_1/ip/req_pend_fifo/req_pend_fifo.xci
# IP: The module: 'req_pend_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/iCloudDrive/course/EE332/lab/final/code/0528/cam2hdmi.gen/sources_1/ip/req_pend_fifo/req_pend_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'req_pend_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/iCloudDrive/course/EE332/lab/final/code/0528/cam2hdmi.gen/sources_1/ip/req_pend_fifo/req_pend_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'req_pend_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
